Updated dev build system
 - do local builds of dnsprobe
 - start dnsprobe alongside api when called by webres6 wrapper
 - some refactoring
 - fix cli client dns display

diff --git a/webres6 b/webres6
--- a/webres6
+++ b/webres6
@@ -10,8 +10,29 @@
 SCRIPT_DIR=$(cd $(dirname $(readlink -f "$0")) && pwd)
 CLI_DIR="$SCRIPT_DIR/cli"
 API_DIR="$SCRIPT_DIR/api"
+DNSPROBE_DIR="$SCRIPT_DIR/dnsprobe"
 PORT=6400
+DNSPROBE_PORT=$(($PORT+53))
+RESULT_CACHE_TTL=30
 
+# Start dnsprobe if not already running
+if [ -z ${DNSPROBE_API_URL} ]; then
+  export DNSPROBE_API_URL="http://[::1]:$DNSPROBE_PORT/"
+  # Check if virtual environment is existing
+  if [ ! -d "$DNSPROBE_DIR/.venv" ]; then
+    echo "Could not find virtual environment for dnsprobe, please run create_virtualenvs.sh first." >&2
+    exit 2
+  fi
+  (
+    cd "$DNSPROBE_DIR"
+    source ".venv/bin/activate"
+    echo "Starting local dnsprobe API $DNSPROBE_API_URL" >&2
+    exec "$DNSPROBE_DIR/.venv/bin/python3" "./dnsprobe.py" "--port=$DNSPROBE_PORT" >/dev/null 1>&2
+  ) &
+  DNSPROBE_SPID=$!
+  echo "Started dnsprobe API with PID $DNSPROBE_SPID" >&2
+  sleep 1
+fi
 
 # Start webres6-server if WEBRES6_API_URL is not set
 if [ -z ${WEBRES6_API_URL} ]; then
@@ -25,13 +46,14 @@ if [ -z ${WEBRES6_API_URL} ]; then
     cd "$API_DIR"
     source ".venv/bin/activate"
     echo "Starting local webres6-api $WEBRES6_API_URL" >&2
-    ENABLE_WHOIS="true" exec "$API_DIR/.venv/bin/python3" "./webres6-api.py" "--port=$PORT" >/dev/null 1>&2
+    ENABLE_WHOIS="true" RESULT_CACHE_TTL="$RESULT_CACHE_TTL" exec "$API_DIR/.venv/bin/python3" "./webres6-api.py" "--port=$PORT" >/dev/null 1>&2
   ) &
   export SPID=$!
   echo "Started webres6-api with PID $SPID" >&2
   sleep 1
-  trap "if [ ! -z $SPID ]; then kill $SPID; fi" EXIT
 fi
+
+trap "if [ ! -z $SPID ]; then kill $SPID; fi; if [ ! -z $DNSPROBE_SPID ]; then kill $DNSPROBE_SPID; fi" EXIT
 
 # Check if virtual environment is existing
 if [ ! -d "$CLI_DIR/.venv" ]; then
